docs/DeveloperGuide.md
#56 Resolve the inconsistent spacing issue
=> Solve uneven spacing issue in use cases

src/main/java/seedu/address/logic/Messages.java, src/main/java/seedu/address/logic/commands/AddCommand.java, src/main/java/seedu/address/logic/commands/EditCommand.java, src/main/java/seedu/address/logic/parser/AddCommandParser.java, src/main/java/seedu/address/logic/parser/CliSyntax.java, src/main/java/seedu/address/logic/parser/EditCommandParser.java, src/main/java/seedu/address/model/company/Company.java, src/main/java/seedu/address/model/company/Deadline.java, src/main/java/seedu/address/model/util/SampleDataUtil.java, src/test/data/JsonSerializableAddressBookTest/duplicateCompanyAddressBook.json, src/test/data/JsonSerializableAddressBookTest/typicalCompaniesAddressBook.json, src/test/java/seedu/address/logic/LogicManagerTest.java, src/test/java/seedu/address/logic/commands/AddCommandTest.java, src/test/java/seedu/address/logic/commands/CommandTestUtil.java, src/test/java/seedu/address/logic/commands/EditCommandTest.java, src/test/java/seedu/address/logic/commands/EditCompanyDescriptorTest.java, src/test/java/seedu/address/logic/commands/FindCommandTest.java, src/test/java/seedu/address/logic/parser/AddCommandParserTest.java, src/test/java/seedu/address/logic/parser/EditCommandParserTest.java, src/test/java/seedu/address/model/AddressBookTest.java, src/test/java/seedu/address/model/ModelManagerTest.java, src/test/java/seedu/address/model/company/CompanyTest.java, src/test/java/seedu/address/model/company/NameContainsKeywordsPredicateTest.java, src/test/java/seedu/address/model/company/UniqueCompanyListTest.java, src/test/java/seedu/address/storage/JsonAdaptedCompanyTest.java, src/test/java/seedu/address/storage/JsonAddressBookStorageTest.java, src/test/java/seedu/address/testutil/CompanyBuilder.java, src/test/java/seedu/address/testutil/CompanyUtil.java, src/test/java/seedu/address/testutil/TypicalCompanies.java
- Update the format of add command. 
- Edit the deadline field to DD-MM-YYYY format for greater intuition. 
- Edit the sample data and test cases to fit context of app (name is company name instead of contacts name; tags to be priority level of internships).
=> Update add command

docs/UserGuide.md, src/main/java/seedu/address/logic/commands/EditCommand.java, src/main/java/seedu/address/logic/parser/EditCommandParser.java, src/test/java/seedu/address/logic/commands/EditCompanyDescriptorTest.java
Reverts AY2324S1-CS2103T-T17-2/tp#89
Build is unsuccessful as some test cases failed
=> Revert "Update Edit Command"

src/main/java/seedu/address/logic/commands/SortCommand.java, src/main/java/seedu/address/logic/parser/AddressBookParser.java, src/main/java/seedu/address/model/AddressBook.java, src/main/java/seedu/address/model/Model.java, src/main/java/seedu/address/model/ModelManager.java, src/main/java/seedu/address/model/company/Deadline.java, src/main/java/seedu/address/model/company/UniqueCompanyList.java, src/main/java/seedu/address/storage/JsonAdaptedCompany.java, src/main/java/seedu/address/ui/CompanyCard.java, src/main/java/seedu/address/ui/CompanyDetailCard.java, src/test/java/seedu/address/logic/commands/AddCommandTest.java, src/test/java/seedu/address/testutil/CompanyBuilder.java, src/test/java/seedu/address/testutil/CompanyUtil.java
- Deadline class now implements the Java Comparable<T> interface
- deadline attribute in Deadline class changed from String to [java.time.LocalDate](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/time/LocalDate.html)
- Sort command has been added
- Deadline class now implements the Comparable interface to allow for easier comparisons to be made between two Deadline objects. The method of comparison is **dependant on LocalDate's implementation of compareTo**. 
- The sort command sorts the companies by the deadline. It modifies the original list of companies in the addressbook and this is IRREVERSIBLE. 
- Intended behavior of sort command to be done in v1.3.
- Closes #87 
No new test cases were added to verify correctness of the sort feature as it is going to be updated …
=> Add sort companies feature

src/main/java/seedu/address/logic/commands/DeleteCommand.java, src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
Edit the success message for delete command
Instead of displaying the full company detail, only the company name will be shown when a company is deleted 
The test cases in DeleteCommandTest were updated
=> Edit success message for delete command

src/test/java/seedu/address/model/company/RecruiterNameTest.java, src/test/java/seedu/address/model/company/RoleTest.java
- Add test cases for Role and RecruiterName fields for Company class. More test cases will have to be added once the fields are updated again in v1.3.
=> Add test cases

build.gradle, src/main/java/seedu/address/MainApp.java
Renamed addressbook.jar to LinkMeIn.jar
Changed version number from 0.0.2 to 1.2.0
- Closes #102
=> Prepare for release v1.2.0

src/main/resources/view/CompanyDetailCard.fxml, src/main/resources/view/DarkTheme.css, src/main/resources/view/MainWindow.fxml
Edit UI for CompanyDetailCard
- Add Company's Information and Recruiter's Information labels
- Update the colour scheme of the CompanyDetailCard to match the CompanyListPanel
- Fix resizing issue of ApplicationStatus field to prevent display of elipsis
=> Edit UI for CompanyDetailCard

src/main/java/seedu/address/logic/commands/FilterCommand.java, src/main/java/seedu/address/logic/parser/AddressBookParser.java, src/main/java/seedu/address/logic/parser/FilterCommandParser.java, src/main/java/seedu/address/model/Model.java, src/main/java/seedu/address/model/ModelManager.java, src/main/java/seedu/address/model/company/ApplicationStatus.java, src/main/java/seedu/address/model/company/ApplicationStatusPredicate.java, src/test/java/seedu/address/logic/commands/AddCommandTest.java, src/test/java/seedu/address/logic/commands/FilterCommandTest.java, src/test/java/seedu/address/logic/parser/AddressBookParserTest.java, src/test/java/seedu/address/logic/parser/FilterCommandParserTest.java, src/test/java/seedu/address/model/company/ApplicationStatusPredicateTest.java
Add a new feature: FilterCommand
FilterCommand allows users to filter the list of companies by application status. 
Let's 
- implement the filter command
- add test cases relevant to the filter command
- change the UI to remove the current viewed company on the left panel as this company might not be in the filtered list
=> Add filter command

docs/UserGuide.md
Reverts AY2324S1-CS2103T-T17-2/tp#118
=> Revert "UserGuide: Update Introduction Section"

src/main/java/seedu/address/logic/commands/ViewCommand.java
=> Implement logging in view function

src/main/java/seedu/address/commons/util/StringUtil.java, src/main/java/seedu/address/logic/Messages.java, src/main/java/seedu/address/logic/commands/DeleteCommand.java, src/main/java/seedu/address/logic/parser/DeleteCommandParser.java, src/main/java/seedu/address/logic/parser/ParserUtil.java, src/main/java/seedu/address/logic/parser/ViewCommandParser.java, src/test/java/seedu/address/commons/util/StringUtilTest.java, src/test/java/seedu/address/logic/commands/DeleteCommandTest.java, src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java, src/test/java/seedu/address/logic/parser/ParserUtilTest.java, src/test/java/seedu/address/logic/parser/ViewCommandParserTest.java
Error messages for view and delete are more specific and user friendly 
Add new messages in Messages class and create new checks in StringUtil. 
Test cases were written for the new method that I create in StringUtil.
=> Improve error message for view and delete command

src/main/java/seedu/address/logic/Messages.java, src/main/java/seedu/address/logic/commands/FilterCommand.java, src/main/java/seedu/address/logic/parser/FilterCommandParser.java, src/main/java/seedu/address/model/company/ApplicationStatus.java, src/test/java/seedu/address/logic/parser/FilterCommandParserTest.java
Update Filter Command
- Update error messages for Filter Command
- [] I have added tests to cover my changes
=> Update error messages for Filter Command

src/main/java/seedu/address/logic/Messages.java, src/main/java/seedu/address/logic/parser/FilterCommandParser.java, src/main/java/seedu/address/model/company/ApplicationStatus.java, src/main/java/seedu/address/model/company/Deadline.java, src/main/java/seedu/address/model/company/Name.java, src/main/java/seedu/address/model/company/Phone.java
- Fix typo for error messages. 
- Add in a duplicate prefix check for FilterCommand, and update error message.
=> Update error messages

src/main/java/seedu/address/logic/commands/RemarkCommand.java, src/main/java/seedu/address/logic/parser/UnremarkCommandParser.java, src/main/java/seedu/address/model/company/Remark.java, src/test/java/seedu/address/logic/commands/RemarkCommandTest.java, src/test/java/seedu/address/logic/parser/UnremarkCommandParserTest.java
Remark section will show "No remarks" when unremark is done. 
Right now, when unremark is called, it clears the remark section. 
With this PR, "No remarks" will be shown instead
=> Unremark feature

src/main/java/seedu/address/MainApp.java
Prepare for release v1.3.0. Existing test passed.
=> Prepare for release v1.3.0

src/main/java/seedu/address/logic/parser/ArgumentTokenizer.java
Allow prefixes to be in uppercase. All test cases passed
=> Fix prefix bug

src/main/java/seedu/address/logic/Messages.java, src/main/java/seedu/address/logic/parser/ParserUtil.java, src/main/java/seedu/address/model/company/Name.java, src/main/java/seedu/address/model/company/Phone.java, src/main/java/seedu/address/model/company/RecruiterName.java, src/main/java/seedu/address/model/company/Role.java, src/main/resources/view/CompanyDetailCard.fxml, src/main/resources/view/CompanyListCard.fxml
Improve edge cases for company fields
- Update company's name, recruiter's name and role to have a maximum of 100 characters (excluding spaces). 
- Update phone number to be between 3 and 20 digits (excluding spaces). 
- Edit UI to allow for longer inputs for company fields by doing wrap text.
=> Update edge cases for company fields

build.gradle, src/main/java/seedu/address/ui/HelpWindow.java, src/main/java/seedu/address/ui/MainWindow.java, src/main/resources/view/HelpWindow.fxml
=> Help command

docs/UserGuide.md
=> Fix formatting for UG

src/main/java/seedu/address/logic/parser/ParserUtil.java, src/main/java/seedu/address/model/company/Phone.java, src/test/java/seedu/address/logic/parser/ParserUtilTest.java, src/test/java/seedu/address/model/company/PhoneTest.java
- Fix bug: Validation regex for Phone field 
- Add test cases for Phone field
=> Fix bug for Phone field

docs/team/tayruxin.md
- Written an overview of project 
- Enhancement implemented 
- Contribution to the UG 
- Contribution to the DG
- Contribution to team-based tasks
- Review/mentoring contributions 
- Contributions beyond the project team
=> Edit PPP draft

docs/UserGuide.md
- Removed table for the different styles of text in "Navigating the user guide" 
- Edited a typo error in quick tour
=> Edit UG formating

docs/AboutUs.md
Added link to PP in about us page
=> Add portfolio link in about us

src/main/java/seedu/address/logic/Messages.java
Fix typo for grammatical error when only 1 company is returned.
=> Fix typo for find result

src/main/java/seedu/address/logic/Messages.java
Fix negative index error message for extreme inputs to be correct mathematically and logically.
Closes #202
=> Fix index error msg

src/main/java/seedu/address/logic/Messages.java, src/main/java/seedu/address/logic/commands/AddCommand.java, src/main/java/seedu/address/logic/commands/EditCommand.java, src/main/java/seedu/address/model/Model.java, src/main/java/seedu/address/model/ModelManager.java, src/main/java/seedu/address/model/company/Name.java, src/main/java/seedu/address/model/company/RecruiterName.java, src/main/java/seedu/address/model/company/Role.java, src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java, src/test/java/seedu/address/logic/commands/AddCommandTest.java, src/test/java/seedu/address/logic/commands/EditCommandTest.java, src/test/java/seedu/address/logic/commands/FindCommandTest.java, src/test/java/seedu/address/logic/commands/stubs/ModelStub.java, src/test/java/seedu/address/logic/commands/stubs/ModelStubAcceptingCompanyAdded.java, src/test/java/seedu/address/logic/commands/stubs/ModelStubWithCompanyInFilteredCompanyList.java, src/test/java/seedu/address/logic/commands/stubs/ModelStubWithCompanyNotInFilteredCompanyList.java, src/test/java/seedu/address/logic/commands/testdata/FindCommandTestCompanies.java, src/test/java/seedu/address/model/company/NameTest.java, src/test/java/seedu/address/model/company/RecruiterNameTest.java, src/test/java/seedu/address/model/company/RoleTest.java
=> Bug fixes of alphanumerics

docs/team/tayruxin.md
The length of PPP exceeds the limit however, with the new edit, the length will be reduced.
=> Edit length of PPP

src/main/java/seedu/address/logic/commands/ClearCommand.java
Removed traces of address book in the clear command error message
Closes #251
=> Fix clear result msg

src/main/java/seedu/address/logic/commands/SortCommand.java, src/main/java/seedu/address/logic/parser/SortCommandParser.java, src/test/java/seedu/address/logic/parser/SortCommandParserTest.java
fix sort command error message. 
closes #237
=> Fix sort command error

src/main/java/seedu/address/logic/Messages.java, src/main/java/seedu/address/logic/parser/ViewCommandParser.java, src/main/java/seedu/address/model/AddressBook.java, src/main/java/seedu/address/model/company/ApplicationStatus.java, src/main/java/seedu/address/ui/CompanyCard.java, src/main/java/seedu/address/ui/CompanyCardUtils.java, src/main/java/seedu/address/ui/CompanyDetailCard.java
- Abstract out the flow pane method in CompanyCard and CompanyDetailCard to prevent repetitive codes
- Edit javadocs
=> Improve code quality

docs/DeveloperGuide.md
- Remove numbering in headers for ease of re-ordering later
- Update Acknowledgement Section
- Update headers to pascal case
- Add planned enhancements and effort section
=> Fix headers and update acknowledgements

docs/UserGuide.md
- rearrange order 
- Notes change to note for single note
- Added FAQ for linux 
- Edit the detail of duplicate checks
=> Organise UG

src/main/java/seedu/address/logic/commands/AddCommand.java, src/main/java/seedu/address/logic/commands/FilterCommand.java
- Add logging statements in Add and Filter Command
=> Add logging statements

docs/UserGuide.md
The image for add command error was wrong previously
=> Add in missing image

docs/DeveloperGuide.md
Similar size and centralise diagram
=> Resize activity diagram

docs/UserGuide.md
Update tagline for duplicate section
=> Update tagline for duplicate section

docs/UserGuide.md
- Change the description for find and sort to be more simple
- Follow the styling format of the UG.
=> Update UG for find and sort sections

docs/UserGuide.md
Minor edits on typo and grammar for UG
=> Update UG: Minor edits

docs/AboutUs.md
- Update formatting and add responsibilities
=> Update About Us Page

docs/UserGuide.md
=> Fix minor errors in UG

docs/team/papataco14.md
Reduce header sizes for everything by one.
=> Fix formatting and intro
